apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fullstack
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
  SECRET_KEY: "${SECRET_KEY}"
  ALGORITHM: "${ALGORITHM}"
  ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES}"
  CORS_ORIGINS: '["http://localhost:3000","http://localhost:30000"]'
