apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fullstack
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort
