apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: fullstack
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
